### ISSUE TITLE
Problem with examples in Chapter 2

### ISSUE THREAD

**Issue by telemachus** [PacktPublishing/System-Programming-Essentials-with-Go#5]
The code examples [for changing_shared_state in Chapter 2](https://github.com/PacktPublishing/System-Programming-Essentials-with-Go/tree/main/ch2/changing-shared-state) don't make sense to me. In particular, here's the `PackItems` function [from example 4](https://github.com/PacktPublishing/System-Programming-Essentials-with-Go/blob/main/ch2/changing-shared-state/example_4/main.go).

```go
func PackItems(totalItems int32) int32 {
	const workers = 2
	const itemsPerWorker = 1000

	var wg sync.WaitGroup

	itemsPacked := 0
	for i := 0; i < workers; i++ {
		wg.Add(1)

		go func(workerID int) {
			defer wg.Done()
			// Simulate the worker packing items into boxes.
			for j := 0; j < itemsPerWorker; j++ {
				atomic.AddInt32(&totalItems, int32(itemsPacked))
			}
		}(i)

	}

	// Wait for all workers to finish.
	wg.Wait()

	return totalItems
}
```

The use of `atomic.AddInt32` may remove the data race, but you're no longer even simulating a worker packing boxes. That is, you never increase `itemsPacked`. You're just (atomically) adding zero to `totalItems` 2000 times. (Your test passes but only because you've switched from `PackItems(0)` in previous examples to `PackItems(2000)`. You're getting back the same number you pass into `PackItems`.)

Did you want something like this?

```go
func PackItems(totalItems int32) int32 {
	const workers = 2
	const itemsPerWorker = 1000

	var wg sync.WaitGroup

	for i := 0; i < workers; i++ {
		wg.Add(1)
		itemsPacked := int32(0)

		go func() {
			defer wg.Done()
			// Simulate the worker packing items into boxes.
			for j := 0; j < itemsPerWorker; j++ {
				atomic.AddInt32(&itemsPacked, 1)
			}
			atomic.AddInt32(&totalItems, itemsPacked)
		}()
	}

	// Wait for all workers to finish.
	wg.Wait()

	return totalItems
}
```

Though at that point, I wonder why we even need the `itemsPacked` variable. Maybe this instead?

```go
func PackItems(totalItems int32) int32 {
	const workers = 2
	const itemsPerWorker = 1000

	var wg sync.WaitGroup

	for i := 0; i < workers; i++ {
		wg.Add(1)

		go func() {
			defer wg.Done()
			// Simulate the worker packing items into boxes.
			for j := 0; j < itemsPerWorker; j++ {
				atomic.AddInt32(&totalItems, 1)
			}
		}()
	}

	// Wait for all workers to finish.
	wg.Wait()

	return totalItems
}
```

**Comment by alexrios** [comment]
Hey @telemachus! Thanks for opening this issue. 

I'm back online this week after some days off, and I'll be sure to take a look with caution tomorrow and ping you back.

**Comment by alexrios** [comment]
> The use of `atomic.AddInt32` may remove the data race, but you're no longer even simulating a worker packing boxes. That is, you never increase `itemsPacked`. You're just (atomically) adding zero to `totalItems` 2000 times. (Your test passes but only because you've switched from `PackItems(0)` in previous examples to `PackItems(2000)`. You're getting back the same number you pass into `PackItems`.)

You're correct. Good catch 🌞 !

> Did you want something like this?
> 
> ```go
> func PackItems(totalItems int32) int32 {
> 	const workers = 2
> 	const itemsPerWorker = 1000
> 
> 	var wg sync.WaitGroup
> 
> 	for i := 0; i < workers; i++ {
> 		wg.Add(1)
> 		itemsPacked := int32(0)
> 
> 		go func() {
> 			defer wg.Done()
> 			// Simulate the worker packing items into boxes.
> 			for j := 0; j < itemsPerWorker; j++ {
> 				atomic.AddInt32(&itemsPacked, 1)
> 			}
> 			atomic.AddInt32(&totalItems, itemsPacked)
> 		}()
> 	}
> 
> 	// Wait for all workers to finish.
> 	wg.Wait()
> 
> 	return totalItems
> }
> ```

Nearly there! Using `AddInt32` will cause a new problem, since it increments the `totalItems` original value (`2000`) with the result of the iterations.

In this case, I'd rather go with `atomic.SwapInt32(&totalItems, itemsPacked)`. It will be a safe operation and be analogous to an attribution.


> Though at that point, I wonder why we even need the `itemsPacked` variable. Maybe this instead?
> 
> ```go
> func PackItems(totalItems int32) int32 {
> 	const workers = 2
> 	const itemsPerWorker = 1000
> 
> 	var wg sync.WaitGroup
> 
> 	for i := 0; i < workers; i++ {
> 		wg.Add(1)
> 
> 		go func() {
> 			defer wg.Done()
> 			// Simulate the worker packing items into boxes.
> 			for j := 0; j < itemsPerWorker; j++ {
> 				atomic.AddInt32(&totalItems, 1)
> 			}
> 		}()
> 	}
> 
> 	// Wait for all workers to finish.
> 	wg.Wait()
> 
> 	return totalItems
> }
> ```

Not really. In this version, we're adding to the original value of `totalItems` (`2000`).

I'm pushing the fixed version. Thanks you 👍🏾

**Comment by zjfsdnu** [comment]
`go version go1.23.4 windows/amd64`

Current code has data race

```
go test -race
==================
WARNING: DATA RACE
Write at 0x00c00010c2fc by goroutine 9:
  sync/atomic.AddInt32()
      C:/Program Files/Go/src/runtime/race_amd64.s:281 +0xb
  sync/atomic.AddInt32()
      <autogenerated>:1 +0x14
  _/C_/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4.PackItems.gowrap1()
      C:/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4/main.go:38 +0x41

Previous read at 0x00c00010c2fc by goroutine 8:
  _/C_/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4.PackItems.func1()
      C:/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4/main.go:37 +0xc4
  _/C_/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4.PackItems.gowrap1()
      C:/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4/main.go:38 +0x41

Goroutine 9 (running) created at:
  _/C_/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4.PackItems()
      C:/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4/main.go:31 +0xc4
  _/C_/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4.TestPackItems()
      C:/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4/main_test.go:8 +0x2e
  testing.tRunner()
      C:/Program Files/Go/src/testing/testing.go:1690 +0x1dd
  testing.(*T).Run.gowrap1()
      C:/Program Files/Go/src/testing/testing.go:1743 +0x44

Goroutine 8 (finished) created at:
  _/C_/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4.PackItems()
      C:/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4/main.go:31 +0xc4
  _/C_/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4.TestPackItems()
      C:/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4/main_test.go:8 +0x2e
  testing.tRunner()
      C:/Program Files/Go/src/testing/testing.go:1690 +0x1dd
  testing.(*T).Run.gowrap1()
      C:/Program Files/Go/src/testing/testing.go:1743 +0x44
==================
--- FAIL: TestPackItems (0.00s)
    testing.go:1399: race detected during execution of test
FAIL
exit status 1
FAIL    _/C_/work/study/go/System-Programming-Essentials-with-Go-main/ch2/changing-shared-state/example_4       0.281s
```

We should move **atomic.SwapInt32(&totalItems, itemsPacked)** after **wg.Wait()**

```go
func PackItems(totalItems int32) int32 {
	const workers = 2
	const itemsPerWorker = 1000

	var wg sync.WaitGroup

	itemsPacked := int32(0)
	for i := 0; i < workers; i++ {
		wg.Add(1)

		go func(workerID int) {
			defer wg.Done()
			// Simulate the worker packing items into boxes.
			for j := 0; j < itemsPerWorker; j++ {
				atomic.AddInt32(&itemsPacked, 1)
			}
		}(i)

	}

	// Wait for all workers to finish.
	wg.Wait()
	atomic.SwapInt32(&totalItems, itemsPacked)

	return totalItems
}
```

**Comment by ryancaplette** [comment]
@alexrios @zjfsdnu @telemachus

I don't have permission to reopen this issue but I have opened a new PR to address and fix the remaining bugs with this issue.

PR: https://github.com/PacktPublishing/System-Programming-Essentials-with-Go/pull/12

Thank you!
