### ISSUE TITLE
ch2/making-sense-of-channels/example_10/main.go running code defers to output suggested in books

### ISSUE THREAD

**Issue by arunkhattri** [PacktPublishing/System-Programming-Essentials-with-Go#8]
`go run main.go ` is giving following output:
`Circus car ride is over!`

**Comment by alexrios** [comment]
Thanks for noticing, @arunkhattri. I'm updating the example to be more didactic and easy to follow.

**Comment by alexrios** [comment]
@arunkhattri Please take a look #9
